bookc/adverts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.AdvertsView.as_view()),
    path("comments/<int:pk>/", views.AddComment.as_view(), name="add_comment"),
    path("<slug:slug>/", views.AdvertDetailView.as_view(), name="advert_detail"),
]

bookc/bookc/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("profile_.urls")),
    path("", include("adverts.urls")),
]

bookc/adverts/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse

from utils.transliteration import transliteration_rus_eng


class Category(models.Model):
    """Категории объявлений"""
    name = models.CharField("Имя", max_length=50, unique=True)
    slug = models.SlugField(
        "url",
        max_length=50,
        unique=True,
        blank=True,
        null=True
    )

    def save(self, *args, **kwargs):
        self.slug = transliteration_rus_eng(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class AdvertType(models.Model):
    """Тип обьявления"""
    name = models.CharField("Имя", max_length=50, unique=True)
    slug = models.SlugField("url", max_length=50, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Тип"
        verbose_name_plural = "Типы"


class Period(models.Model):
    """Срок для объявления"""
    name = models.CharField("Имя", max_length=50, unique=True)
    slug = models.SlugField("url", max_length=50, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Срок"
        verbose_name_plural = "Сроки"
        ordering = ["id"]


class Advert(models.Model):
    """Объявление"""
    user = models.ForeignKey(
        User,
        verbose_name="Пользователь",
        on_delete=models.CASCADE
    )
    category = models.ManyToManyField(
        Category, verbose_name="Категория"
    )
    filters = models.ForeignKey(
        AdvertType, verbose_name="Фильтр", on_delete=models.CASCADE
    )
    period = models.ForeignKey(
        Period, verbose_name="Срок", on_delete=models.CASCADE
    )
    subject = models.CharField("Тема", max_length=200)
    text = models.TextField("Объявление", max_length=10000)

    images = models.ForeignKey(
        'gallery.ImageSet',
        verbose_name="Изображения",
        blank=True,
        null=True,
        on_delete=models.SET_NULL
    )

    price = models.DecimalField(
        "Цена",
        max_digits=8,
        decimal_places=2,
        default=0.00
    )
    created = models.DateTimeField("Дата создания", auto_now_add=True)
    moderation = models.BooleanField("Модерация", default=False)
    slug = models.SlugField(
        "url",
        max_length=200,
        unique=True,
        blank=True,
        null=True
    )

    def save(self, *args, **kwargs):
        self.slug = ("advert" + transliteration_rus_eng(self.id) + "-" + str(self.user.id))
        super().save(*args, **kwargs)

    def __str__(self):
        return self.subject

    def get_absolute_url(self):
        return reverse("advert_detail", kwargs={"slug": self.slug})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = CommentForm()
        return context

    class Meta:
        verbose_name = "Объявление"
        verbose_name_plural = "Объявления"


class Comments(models.Model):
    """Комментарии"""
    name = models.CharField("Имя", max_length=50)
    text = models.TextField("Сообщение", max_length=400)
    created = models.DateTimeField("Дата создания", auto_now_add=True)
    advert = models.ForeignKey(Advert, verbose_name="Объявление", on_delete=models.CASCADE)

    def __str__(self):
        return self.name + " | " + str(self.advert)

    class Meta:
        verbose_name = "Комментарий"
        verbose_name_plural = "Коментарии"

bookc/adverts/forms.py
from django import forms

from .models import Comments


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ("name", "text")

bookc/adverts/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.base import View
from django.shortcuts import redirect

from .models import Advert
from .forms import CommentForm


class AdvertsView(ListView):
    '''Список обьявлений'''
    model = Advert
    queryset = Advert.objects.filter(moderation=True)


class AdvertDetailView(DetailView):
    """Объявление"""
    model = Advert
    queryset = Advert.objects.filter(moderation=True)
    slug_field = "slug"


class AddComment(View):
    """Комментарии"""
    def post(self, request, pk):
        form = CommentForm(request.POST)
        advert = Advert.objects.get(id=pk)
        if form.is_valid():
            form = form.save(commit=False)
            form.advert = advert
            form.save()
        return redirect(advert.get_absolute_url())

bookc/adverts/templates/adverts/advert_detail.html
{% extends 'adverts/base.html' %}

{% block title %}
{{advert.subject}}
{% endblock title %}

{% block content %}
<p>{{advert.filters}}</p>
{{advert.user.username}}
<p>
{% for image in advert.images.photos.all%}
<img src=media/{{image.image.name}} alt = "{{image.name}}">
{% endfor %}
</p>

{% for category in advert.category.all%}
| {{category}}
{% endfor %}
</p>


<p>{{advert.text}}</p>
<p>{{advert.created}}</p>

<hr>
<form method="post" action="{% url 'add_comment' advert.id %}">
    {% csrf_token %}

    <textarea name="name" rows=1 cols=80 placeholder="Ваше имя"></textarea>
    <br>
    <textarea name="text" rows=5 cols=80 placeholder="Комментарий"></textarea>
    <br>
    <button type="submit" class="btn btn-primary">Отправить</button>
</form>


{% for comment in advert.comments_set.all %}
<hr>
<p>{{comment.name}}</p>
<p>{{comment.text}}</p>
<p>{{comment.created}}</p>

{% endfor %}
{% endblock content %}

bookc/adverts/templates/adverts/advert_list.html
{% extends 'adverts/base.html' %}


{% block title %}
    Объявления
{% endblock title %}

{% block content %}
{% for advert in advert_list%}
<p>{{advert.filters}}</p>
<a href={{ advert.get_absolute_url }}>
    <h2>{{advert.subject}}</h2>
</a>

<p>
{% for category in advert.category.all%}
| {{category}}
{% endfor %}
</p>

<p>{{advert.created}}</p>
<hr>
{%endfor%}


{% endblock content %}

bookc/adverts/templates/adverts/base.html
<html>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script> 
    <title>
        {% block title %}
        {% endblock title %}  
    </title>

    <body>
        
        {% if user.is_authenticated %}
        <a href = "http://127.0.0.1:8000/profile/">Профиль</a>
        <a href = "http://127.0.0.1:8000/logout/">Выйти</a><hr>
        {% else %}
        <a href = "http://127.0.0.1:8000/login/">Войти</a><br><hr>
        {% endif%}

        {%block content %}
        {%endblock content %}
    </body>

</html>